/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/[companyCode]/': RouteRecordInfo<
      '/[companyCode]/',
      '/:companyCode',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/admin/impersonate/[[companyId]]': RouteRecordInfo<
      '/[companyCode]/admin/impersonate/[[companyId]]',
      '/:companyCode/admin/impersonate/:companyId?',
      { companyCode: ParamValue<true>, companyId?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, companyId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/api-keys': RouteRecordInfo<
      '/[companyCode]/api-keys',
      '/:companyCode/api-keys',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/approval-workflows/[[id]]': RouteRecordInfo<
      '/[companyCode]/approval-workflows/[[id]]',
      '/:companyCode/approval-workflows/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/audit-logs': RouteRecordInfo<
      '/[companyCode]/audit-logs',
      '/:companyCode/audit-logs',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/dashboard': RouteRecordInfo<
      '/[companyCode]/dashboard',
      '/:companyCode/dashboard',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/departments': RouteRecordInfo<
      '/[companyCode]/departments',
      '/:companyCode/departments',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/document-templates/[[id]]': RouteRecordInfo<
      '/[companyCode]/document-templates/[[id]]',
      '/:companyCode/document-templates/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/documents/[[id]]': RouteRecordInfo<
      '/[companyCode]/documents/[[id]]',
      '/:companyCode/documents/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/form-templates': RouteRecordInfo<
      '/[companyCode]/form-templates',
      '/:companyCode/form-templates',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/groups/[[id]]': RouteRecordInfo<
      '/[companyCode]/groups/[[id]]',
      '/:companyCode/groups/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/notifications': RouteRecordInfo<
      '/[companyCode]/notifications',
      '/:companyCode/notifications',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/option-sets/[[id]]': RouteRecordInfo<
      '/[companyCode]/option-sets/[[id]]',
      '/:companyCode/option-sets/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/records': RouteRecordInfo<
      '/[companyCode]/records',
      '/:companyCode/records',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/roles/[[id]]': RouteRecordInfo<
      '/[companyCode]/roles/[[id]]',
      '/:companyCode/roles/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/settings': RouteRecordInfo<
      '/[companyCode]/settings',
      '/:companyCode/settings',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/sites': RouteRecordInfo<
      '/[companyCode]/sites',
      '/:companyCode/sites',
      { companyCode: ParamValue<true> },
      { companyCode: ParamValue<false> },
      | never
    >,
    '/[companyCode]/suppliers/[[id]]': RouteRecordInfo<
      '/[companyCode]/suppliers/[[id]]',
      '/:companyCode/suppliers/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/task-instances/[[id]]': RouteRecordInfo<
      '/[companyCode]/task-instances/[[id]]',
      '/:companyCode/task-instances/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/templates/[[id]]': RouteRecordInfo<
      '/[companyCode]/templates/[[id]]',
      '/:companyCode/templates/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/users/[[id]]': RouteRecordInfo<
      '/[companyCode]/users/[[id]]',
      '/:companyCode/users/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/[companyCode]/workflow-instances/[[id]]': RouteRecordInfo<
      '/[companyCode]/workflow-instances/[[id]]',
      '/:companyCode/workflow-instances/:id?',
      { companyCode: ParamValue<true>, id?: ParamValueZeroOrOne<true> },
      { companyCode: ParamValue<false>, id?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/accept-invitation': RouteRecordInfo<
      '/accept-invitation',
      '/accept-invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password': RouteRecordInfo<
      '/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/form/[templateId]': RouteRecordInfo<
      '/form/[templateId]',
      '/form/:templateId',
      { templateId: ParamValue<true> },
      { templateId: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signin': RouteRecordInfo<
      '/signin',
      '/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/[companyCode]/index.vue': {
      routes:
        | '/[companyCode]/'
      views:
        | never
    }
    'src/pages/[companyCode]/admin/impersonate/[[companyId]].vue': {
      routes:
        | '/[companyCode]/admin/impersonate/[[companyId]]'
      views:
        | never
    }
    'src/pages/[companyCode]/api-keys.vue': {
      routes:
        | '/[companyCode]/api-keys'
      views:
        | never
    }
    'src/pages/[companyCode]/approval-workflows/[[id]].vue': {
      routes:
        | '/[companyCode]/approval-workflows/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/audit-logs.vue': {
      routes:
        | '/[companyCode]/audit-logs'
      views:
        | never
    }
    'src/pages/[companyCode]/dashboard.vue': {
      routes:
        | '/[companyCode]/dashboard'
      views:
        | never
    }
    'src/pages/[companyCode]/departments.vue': {
      routes:
        | '/[companyCode]/departments'
      views:
        | never
    }
    'src/pages/[companyCode]/document-templates/[[id]].vue': {
      routes:
        | '/[companyCode]/document-templates/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/documents/[[id]].vue': {
      routes:
        | '/[companyCode]/documents/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/form-templates.vue': {
      routes:
        | '/[companyCode]/form-templates'
      views:
        | never
    }
    'src/pages/[companyCode]/groups/[[id]].vue': {
      routes:
        | '/[companyCode]/groups/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/notifications.vue': {
      routes:
        | '/[companyCode]/notifications'
      views:
        | never
    }
    'src/pages/[companyCode]/option-sets/[[id]].vue': {
      routes:
        | '/[companyCode]/option-sets/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/records.vue': {
      routes:
        | '/[companyCode]/records'
      views:
        | never
    }
    'src/pages/[companyCode]/roles/[[id]].vue': {
      routes:
        | '/[companyCode]/roles/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/settings.vue': {
      routes:
        | '/[companyCode]/settings'
      views:
        | never
    }
    'src/pages/[companyCode]/sites.vue': {
      routes:
        | '/[companyCode]/sites'
      views:
        | never
    }
    'src/pages/[companyCode]/suppliers/[[id]].vue': {
      routes:
        | '/[companyCode]/suppliers/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/task-instances/[[id]].vue': {
      routes:
        | '/[companyCode]/task-instances/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/templates/[[id]].vue': {
      routes:
        | '/[companyCode]/templates/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/users/[[id]].vue': {
      routes:
        | '/[companyCode]/users/[[id]]'
      views:
        | never
    }
    'src/pages/[companyCode]/workflow-instances/[[id]].vue': {
      routes:
        | '/[companyCode]/workflow-instances/[[id]]'
      views:
        | never
    }
    'src/pages/accept-invitation.vue': {
      routes:
        | '/accept-invitation'
      views:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | '/forgot-password'
      views:
        | never
    }
    'src/pages/form/[templateId].vue': {
      routes:
        | '/form/[templateId]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
    }
    'src/pages/signin.vue': {
      routes:
        | '/signin'
      views:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
